# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3week' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3week
  pod 'RxSwift'
  pod 'RxCocoa'

  target '3weekTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3weekUITests' do
    # Pods for testing
  end

end
